export const TRANSACTION_REQUEST = "TRANSACTION_REQUEST"
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS"
export const TRANSACTION_FALIURE = "TRANSACTION_FALIURE"

export const OVERVIEW_REQUEST = "OVERVIEW_REQUEST"
export const OVERVIEW_SUCCESS = "OVERVIEW_SUCCESS"
export const OVERVIEW_FALIURE = "OVERVIEW_FALIURE"